# Generated by Django 2.1 on 2019-08-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('create_time', models.DateTimeField()),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookInfoLocal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('book_name', models.CharField(blank=True, max_length=200, null=True)),
                ('book_orig_name', models.CharField(blank=True, max_length=200, null=True)),
                ('book_subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('book_poster_url', models.CharField(blank=True, max_length=400, null=True)),
                ('book_poster_name', models.CharField(blank=True, max_length=200, null=True)),
                ('publish_year', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=500, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('douban_average', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('douban_rators', models.BigIntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('hot', models.IntegerField(blank=True, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
                ('name_alias', models.CharField(blank=True, max_length=1000, null=True)),
                ('relative_book_source_id', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'book_info_local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('create_time', models.DateTimeField()),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieInfoLocal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('movie_name', models.CharField(blank=True, max_length=200, null=True)),
                ('movie_orig_name', models.CharField(blank=True, max_length=200, null=True)),
                ('movie_poster_url', models.CharField(blank=True, max_length=400, null=True)),
                ('movie_poster_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('release_time', models.CharField(max_length=200)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('actors', models.CharField(blank=True, max_length=2000, null=True)),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('douban_average', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('douban_rators', models.BigIntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField()),
                ('imdb', models.CharField(blank=True, max_length=50, null=True)),
                ('be_on', models.IntegerField(blank=True, null=True)),
                ('hot', models.IntegerField(blank=True, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=200, null=True)),
                ('director_show', models.CharField(blank=True, max_length=500, null=True)),
                ('create_time', models.DateTimeField()),
                ('name_alias', models.CharField(blank=True, max_length=1000, null=True)),
                ('relative_movie_source_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie_info_local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TvInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('create_time', models.DateTimeField()),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tv_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TvInfoLocal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tv_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tv_orig_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tv_poster_url', models.CharField(blank=True, max_length=400, null=True)),
                ('tv_poster_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('release_time', models.CharField(max_length=200)),
                ('director', models.CharField(blank=True, max_length=2000, null=True)),
                ('actors', models.CharField(blank=True, max_length=4000, null=True)),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('imdb', models.CharField(blank=True, max_length=50, null=True)),
                ('douban_average', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('douban_rators', models.BigIntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField()),
                ('hot', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
                ('season_id', models.TextField(blank=True, null=True)),
                ('season_index', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=200, null=True)),
                ('create_time', models.DateTimeField()),
                ('name_alias', models.CharField(blank=True, max_length=1000, null=True)),
                ('relative_tv_source_id', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'tv_info_local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('permission', models.TextField(blank=True, null=True)),
                ('role', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
