# Generated by Django 2.2.4 on 2019-08-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='question_text',
        ),
    ]
